import { useState } from "react";
import { Button, Card, Section, StatusTag } from "@prototype/design-system";
import { PrototypeIcon } from "@prototype/icons";
import { getPrototypeView, PrototypePanel, PrototypeState } from "@prototype/runtime";

type Tab = "home" | "store" | "mall" | "care" | "me";

const tabs: Array<{ id: Tab; label: string; icon: "home" | "modules" | "success" | "profile" }> = [
  { id: "home", label: "首页", icon: "home" },
  { id: "store", label: "门店", icon: "home" },
  { id: "mall", label: "商城", icon: "modules" },
  { id: "care", label: "抗衰", icon: "success" },
  { id: "me", label: "我的", icon: "profile" },
];

export function App() {
  const view = getPrototypeView();
  const [tab, setTab] = useState<Tab>("home");
  const [notice, setNotice] = useState("");
  const title = tabs.find((item) => item.id === tab)?.label ?? "首页";
  const go = (next: Tab) => { setTab(next); setNotice(""); window.scrollTo({ top: 0, behavior: "smooth" }); };

  return <div className="min-h-[100dvh] bg-[var(--color-background)] text-[var(--color-text-primary)]">
    <header className="sticky top-0 z-20 border-b border-[var(--color-border)] bg-[var(--color-surface)]/95 pt-[env(safe-area-inset-top)] backdrop-blur"><div className="mx-auto flex min-h-14 max-w-md items-center justify-between px-4"><div><p className="text-xs font-medium text-[var(--color-primary)]">LOCAL LIFE · V0.1</p><h1 className="text-base font-semibold">{title}</h1></div><button aria-label="消息" className="flex min-h-[44px] min-w-[44px] items-center justify-center"><PrototypeIcon name="info" size={19} /></button></div></header>
    <PrototypeState view={view}><main className="mx-auto max-w-md space-y-6 px-4 py-5 pb-24">
      {tab === "home" && <><section className="rounded-[var(--radius-overlay)] bg-[var(--color-primary)] p-5 text-white"><div className="flex items-center justify-between"><StatusTag>统一会员 ID · 8888</StatusTag><span className="text-xs text-white/75">银卡会员</span></div><h2 className="mt-5 text-2xl font-semibold">今天，去附近的生活场景。</h2><p className="mt-2 text-sm leading-6 text-white/80">门店自提、线上配送、智慧抗衰，一个账号全部连通。</p><div className="mt-5 flex gap-2"><Button onClick={() => go("store")} className="bg-white text-[var(--color-primary-pressed)]">去门店自提</Button><button onClick={() => go("care")} className="min-h-[44px] rounded-[var(--radius-control)] border border-white/35 px-4 text-sm">领抗衰体验券</button></div></section><Section title="三个生活入口"><div className="grid grid-cols-3 gap-3">{[{id:"store" as Tab,icon:"home" as const,label:"门店自提",desc:"附近取货"},{id:"mall" as Tab,icon:"modules" as const,label:"线上商城",desc:"全国配送"},{id:"care" as Tab,icon:"success" as const,label:"智慧抗衰",desc:"检测体验"}].map((item) => <button key={item.id} onClick={() => go(item.id)} className="flex min-h-32 flex-col items-start justify-between rounded-[var(--radius-container)] border border-[var(--color-border)] bg-[var(--color-surface)] p-3 text-left"><PrototypeIcon name={item.icon} size={22} /><span><strong className="block text-sm">{item.label}</strong><small className="mt-1 block text-xs text-[var(--color-text-tertiary)]">{item.desc}</small></span></button>)}</div></Section><Card><p className="font-medium">到店自提有额外积分</p><p className="mt-1 text-sm leading-6 text-[var(--color-text-secondary)]">完成一次自提，获得 100 积分和到店礼。</p><button onClick={() => go("store")} className="mt-3 text-sm font-medium text-[var(--color-primary-pressed)]">查看附近门店 →</button></Card></>}
      {tab === "store" && <><div className="flex items-end justify-between"><div><p className="text-sm text-[var(--color-text-secondary)]">选择一个合作载体</p><h2 className="mt-1 text-2xl font-semibold">附近门店</h2></div><StatusTag tone="success">定位已开启</StatusTag></div>{["云岭社区店", "南岸生活馆"].map((name) => <Card key={name}><div className="flex items-start justify-between"><div><h3 className="font-semibold">{name}</h3><p className="mt-1 text-sm text-[var(--color-text-secondary)]">距你 {name === "云岭社区店" ? "0.8" : "2.4"} km · 可自提 · 抗衰检测</p></div><StatusTag tone="success">营业中</StatusTag></div><Button className="mt-4 w-full" onClick={() => setNotice(`${name} · 提货码 LL-1024 · 待到店核销`)}>选择并自提</Button></Card>)}{notice && <Card className="border-[var(--color-success)] bg-[var(--color-success-bg)]"><StatusTag tone="success">模拟订单已创建</StatusTag><p className="mt-3 text-sm">{notice}</p></Card>}</>}
      {tab === "mall" && <><div className="flex items-end justify-between"><div><p className="text-sm text-[var(--color-text-secondary)]">线上商城</p><h2 className="mt-1 text-2xl font-semibold">精选生活好物</h2></div><StatusTag>全国一件代发</StatusTag></div><div className="grid grid-cols-2 gap-3">{["头皮养护套装", "日常清洁组合", "轻盈生活组合", "肌肤护理体验"].map((name, i) => <Card key={name} className="p-3"><div className="flex aspect-square items-center justify-center rounded-[var(--radius-control)] bg-[var(--color-surface-subtle)] text-2xl">{name.slice(0, 1)}</div><h3 className="mt-3 text-sm font-semibold">{name}</h3><p className="mt-1 font-semibold text-[var(--color-primary-pressed)]">¥{[129, 69, 99, 39][i]}</p><button onClick={() => setNotice("商品已加入购物车，可配送到家或到店")} className="mt-3 min-h-[40px] w-full rounded-[var(--radius-control)] bg-[var(--color-primary)] text-sm font-medium text-white">加入购物车</button></Card>)}</div>{notice && <Card className="border-[var(--color-primary)]"><p className="text-sm font-medium">{notice}</p><Button className="mt-3" onClick={() => setNotice("模拟订单已提交，数据已归集至统一用户 ID")}>去结算</Button></Card>}</>}
      {tab === "care" && <><section className="rounded-[var(--radius-overlay)] bg-[#17202A] p-5 text-white"><StatusTag tone="success">店中店 · 基础检测</StatusTag><h2 className="mt-5 text-2xl font-semibold">看见你的生活状态</h2><p className="mt-2 text-sm leading-6 text-white/70">在附近合作门店完成基础检测，报告同步到本地生活账号。</p><button onClick={() => setNotice("体验券已领取，可选择全国合作门店")} className="mt-5 min-h-[44px] rounded-[var(--radius-control)] bg-white px-4 text-sm font-medium text-[#17202A]">领取免费体验券</button></section><Card><div className="flex items-center justify-between"><div><p className="font-medium">我的检测报告</p><p className="mt-1 text-sm text-[var(--color-text-secondary)]">最近一次：2026.08.27 · 云岭社区店</p></div><StatusTag>基础结果</StatusTag></div><button onClick={() => setNotice("头皮状态：基础护理建议。仅用于概念演示，不代表实时或医疗诊断。")} className="mt-4 text-sm font-medium text-[var(--color-primary-pressed)]">查看报告 →</button></Card>{notice && <Card className="border-[var(--color-primary)]"><p className="text-sm leading-6">{notice}</p></Card>}</>}
      {tab === "me" && <><section className="rounded-[var(--radius-overlay)] bg-[var(--color-surface)] p-5"><div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-full bg-[var(--color-brand-subtle)] text-lg font-semibold text-[var(--color-primary-pressed)]">林</div><div><h2 className="font-semibold">林女士</h2><p className="mt-1 text-sm text-[var(--color-text-secondary)]">统一会员 ID · LL-8888</p></div><StatusTag tone="success">银卡</StatusTag></div><div className="mt-5 grid grid-cols-3 gap-3 border-t border-[var(--color-border)] pt-4 text-center"><div><strong className="block text-lg">1,280</strong><span className="text-xs text-[var(--color-text-tertiary)]">积分</span></div><div><strong className="block text-lg">3</strong><span className="text-xs text-[var(--color-text-tertiary)]">优惠券</span></div><div><strong className="block text-lg">2</strong><span className="text-xs text-[var(--color-text-tertiary)]">体验券</span></div></div></section><Section title="我的记录"><div className="grid grid-cols-2 gap-3">{["订单记录", "积分明细", "优惠券", "检测报告"].map((label) => <button key={label} className="flex min-h-20 items-center justify-between rounded-[var(--radius-container)] border border-[var(--color-border)] bg-[var(--color-surface)] px-4 text-sm font-medium"><span>{label}</span><span className="text-[var(--color-text-tertiary)]">›</span></button>)}</div></Section></>}
    </main></PrototypeState><nav className="fixed inset-x-0 bottom-0 z-30 mx-auto flex min-h-16 max-w-md border-t border-[var(--color-border)] bg-[var(--color-surface)] pb-[env(safe-area-inset-bottom)]">{tabs.map((item) => <button key={item.id} onClick={() => go(item.id)} className={`flex flex-1 flex-col items-center justify-center gap-1 text-xs ${tab === item.id ? "font-medium text-[var(--color-primary)]" : "text-[var(--color-text-tertiary)]"}`}><PrototypeIcon name={item.icon} size={20} />{item.label}</button>)}</nav><PrototypePanel /></div>;
}
